name: news_app
description: A new drug cards application for the uniformed services university.


version: 5.2.0

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  
  font_awesome_flutter: ^8.11.0
  dots_indicator: ^1.2.0
  url_launcher: ^5.7.10
  firebase_auth: ^0.18.4+1
  provider: ^4.3.2+3
  
  intl: ^0.16.1
  cached_network_image: ^2.5.0
  http: ^0.12.2
  shared_preferences: ^0.5.12+4
  md2_tab_indicator: ^1.0.2
  flutter_html: ^1.1.1
  shimmer: ^1.1.2
  firebase_messaging: ^7.0.3
  share: ^0.6.5+4
  flutter_icons: ^1.1.0
  introduction_screen: ^1.0.9
  connectivity: ^2.0.2
  launch_review: ^2.0.0
  cloud_firestore: ^0.14.4
  toast: ^0.1.5
  badges: ^1.1.6
  flutter_staggered_animations: ^0.1.2
  baseconvert: ^1.0.2
  google_fonts: ^1.1.1
  

dev_dependencies:
  flutter_automation: ^1.4.0
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.8.1
  

  flutter_test:
    sdk: flutter



flutter_native_splash:
  android: false
  # image: assets/splash.png
  color: "#ffffff"


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"


  


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/news1.png
    - assets/news2.png
    - assets/news3.png
    - assets/news4.png
    - assets/news5.png
    - assets/news6.png
    - assets/news7.png
    - assets/splash.png
    - assets/icon.png





  fonts:
    
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
          




    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 500
